codereview notion
GospodinPromise/123 pull request #6
Opened 2024-02-22 02:04 UTC by spendy-github

2024-02-24 14:54 UTC, greatstudentkaze requested changes

2024-02-24 14:54 UTC, greatstudentkaze commented on index.html
> +    <form class="feedback__application" action="#popup" method="post">
ты по-моему чето перепутал

2024-02-24 14:54 UTC, greatstudentkaze commented on index.html
> +    <div class="header__menu">
сделай кнопкой, оно же кликается и что-то происходит

2024-02-26 21:12 UTC, spendy-github commented on blocks/about.css
> +@media screen and (max-width:800px) {
добавил везде

2024-02-26 21:12 UTC, spendy-github commented on blocks/body.css
> +.second--grid {
ща просто грид

2024-02-26 21:12 UTC, spendy-github commented on blocks/body.css
> +.second--grid {
просто тестил

2024-02-26 21:16 UTC, spendy-github commented on blocks/feedback.css
> +    opacity: 50%;
сделал

2024-02-26 21:16 UTC, spendy-github commented on blocks/feedback.css
> +    color: var(--white)
поставил

2024-02-26 21:45 UTC, spendy-github commented on blocks/feedback.css
> +.popup{
сделал

2024-02-26 21:45 UTC, spendy-github commented on blocks/variables.css
> -    --primary-font: Verdana, sans-serif;
не нужен

2024-02-26 21:48 UTC, spendy-github commented on header-menu.js
> +    document.querySelector('.header__list').classList.toggle('open');
сделал

2024-02-26 21:50 UTC, spendy-github commented on header-menu.js
> +    this.classList.toggle('active');
убрал зис. это ваще ютубера который учит яваскрипту код жи эс

2024-02-26 22:04 UTC, spendy-github commented on index.html
> +    <form class="feedback__application" action="#popup" method="post">
не . пусть так будет пока я не получу знание явы . если есть какой то гайд человеческий как сделать при клике на кнопку выпадающий попап

2024-02-26 22:04 UTC, spendy-github commented on header-menu.js
> +    this.classList.toggle('active');
сделал

2024-02-26 22:05 UTC, spendy-github commented on index.html
> +    <form class="feedback__application" action="#popup" method="post">
то можешь скинуть я хз

2024-02-26 22:11 UTC, spendy-github commented on index.html
> +    <div class="header__menu">
сделал

2024-03-02 21:40 UTC, greatstudentkaze commented on index.html
> +    <div class="header__menu">
нужно type="button" еще задавать кнопкам

иначе по дефолту они type="submit"

2024-03-02 21:41 UTC, greatstudentkaze commented on index.html
> +    <form class="feedback__application" action="#popup" method="post">
https://youtu.be/f_4kJ_Vu7fo?si=520MMjygPbBvn15D например

2024-03-02 21:42 UTC, greatstudentkaze commented on header-menu.js
> +    this.classList.toggle('active');
ты не указал в аргументаx event:

```
headerMenuElement.addEventListener('click', function(event) {
    event.currentTarget.classList.toggle('active');
    ...
})
```

2024-03-02 21:43 UTC, greatstudentkaze commented on header-menu.js
> +const headerBackgroundElement = document.querySelector('.header__background');
а этот зачем? мне кажется, можно без него обойтись

2024-03-03 07:00 UTC, PASHANOJ commented on header-menu.js
> +    this.classList.toggle('active');
![image](https://github.com/PASHANOJ/123/assets/158532470/f030bad5-0901-4b73-b983-0c09a6ecaa77)
указавки

2024-03-03 07:03 UTC, PASHANOJ commented on index.html
> +    <div class="header__menu">
задал

2024-03-03 07:05 UTC, PASHANOJ commented on header-menu.js
> +const headerBackgroundElement = document.querySelector('.header__background');
все ок.пусть так и будет. акцент на меню становится

2024-03-03 07:39 UTC, PASHANOJ commented on index.html
> +    <form class="feedback__application" action="#popup" method="post">
я сам сделал уже. я уже сам знаю жи эс

2024-03-08 20:41 UTC, merged